# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information

workflows:
  react-native-ios:
    name: iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      node: 16.13.2
      xcode: 13.2.1
      cocoapods: 1.11.2
    scripts:
      - name: Install npm dependencies
        script: yarn install --frozen-lockfile
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: xCode build
        script: |
          cd ios
          xcodebuild clean archive -workspace testCiCdReactNative.xcworkspace -scheme testCiCdReactNative -archivePath testCiCdReactNative.xcarchive CODE_SIGNING_ALLOWED=NO | xcpretty
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

  react-native-android:
      name: Android Workflow
      # `mac_pro` - Building on Mac Pro is a paid feature. Please enable billing to run builds on Mac Pro.
      instance_type:  mac_mini
      environment:
          node: 16.13.2
      cache:
        cache_paths:
          - ~/.gradle/caches
          - ~/.cache/yarn/v6

      scripts:
          - yarn install --frozen-lockfile
          - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
          - cd android && ./gradlew bundleRelease assembleRelease
      artifacts:
          - android/app/build/outputs/**/*.apk
          - android/app/build/outputs/**/*.aab
